(function(){var z=function(e){return e?"string"==typeof e?[e]:Array.prototype.slice.call(e):[]},A=function(e,l){for(var a=0;a<e.length;a++)if(e[a]==l)return!0;return!1},B=function(e,l,a){for(var d,b=[],c=e.x,f=e.y,k=">",g=0,h;g<a.length;g++)if(d=a.charAt(g),h=a.substr(g),/^[><+\\-]$/.test(d)){k=d;">"==d?c+=e.cell.colSpan:"<"==d?c--:"+"==d?f--:"-"==d?f+=e.cell.rowSpan:"\\"==d&&(f+=e.cell.rowSpan,c+=e.cell.colSpan);if(0>f||f>=l.length||0>c||c>=l[f].length)return[];e=l[f][c];e.refCell&&(e=e.cell);c=
e.x;f=e.y}else if(d=/^\d+[:a-z]*/i.exec(h))if(h=parseInt(/^\d/.exec(h)[0],10),0===h&&0===g)b.push(e),g+=d[0].length-1;else for(var m=0;m<h;m++){if(0<m){d=k;">"==d?c+=e.cell.colSpan:"<"==d?c--:"+"==d?f--:"-"==d?f+=e.cell.rowSpan:"\\"==d&&(f+=e.cell.rowSpan,c+=e.cell.colSpan);if(0>f||f>=l.length||0>c||c>=l[f].length)return[];e=l[f][c];e.refCell&&(e=e.cell);c=e.x;f=e.y}b.push(e)}else if(/[.]{3}\s*$/.test(h))return b.concat(B(e,l,a));return b},C=function(e){for(var l={},a=[],d=[],b=0,c;b<e.length;b++)c=
e[b],l[1E9*c.y+c.x]=c.cell;for(b in l)l.hasOwnProperty(b)&&a.push({order:b,cell:l[b]});a.sort(function(a,b){return a.order-b.order});for(b=0;b<a.length;b++)d.push(a[b].cell);return d},n=function(e){var l={};this.element=e;this.isAChildCell=function(a){if(!n.isACell(a))return!1;for(;a=a.parentElement;){if(a==this.element)return!0;if(n.isACell(a))break}return!1};this.clearCache=function(){l={}};this.removeCol=function(a){a||0===a||"0"===a||(a=-1);for(var d=this.matrix(),b=0;b<d.length;b++){var c=d[b];
if(0>a){var f=c.length+a;0>f&&(f=0)}else f=a>=c.length?c.length-1:a;if(f=c[f])b+=(f.refCell||f).cell.rowSpan-1,f.refCell?--f.refCell.cell.colSpan:1<f.cell.colSpan?--f.cell.colSpan:f.cell.parentElement.removeChild(f.cell)}};this.removeRow=function(a){a||0===a||"0"===a||(a=-1);var d=this.element,b=this.matrix();0>a?(a=b.length+a,0>a&&(a=0)):a>=b.length&&(a=b.length-1);for(var c=b[a],b=b[a+1],f=0;f<c.length;f++){var k=c[f];if(k.refCell)1<k.refCell.cell.rowSpan&&--k.refCell.cell.rowSpan;else if(1<k.cell.rowSpan&&
b){0!==k.cell.rowSpan&&--k.cell.rowSpan;for(var g=b[f],h=f;h<b.length;h++)b[h].cell&&(g=b[h].cell,h=b.length);d.rows[a+1].insertBefore(k.cell,g)}f+=(k.refCell||k).cell.colSpan-1}d.rows[a].parentElement.removeChild(d.rows[a])};this.insertCol=function(a,d){a||0===a||"0"===a||(a=-1);for(var b=this.element,c=this.matrix(),f=0;f<c.length;f++){var k=c[f];if(0>a){var g=k.length+a+1;0>g&&(g=0)}else g=a>k.length?k.length:a;var k=0===g?c[f][g]:c[f][g-1],h=c[f][g];if(h&&h.refCell)h.refCell.cell.colSpan+=1,f+=
h.refCell.cell.rowSpan-1;else{var e=f;k?(k=k.cell||k.refCell,g=document.createElement(k.tagName),g.rowSpan=k.rowSpan,f+=k.rowSpan-1):g=document.createElement("TD");d&&d.call(this,g);b.rows[e].insertBefore(g,h?h.cell:null)}}};this.insertRow=function(a,d){var b;a||0===a||"0"===a||(a=-1);var c=this.element,f=document.createElement("tr"),k=this.matrix();0>a?(a=k.length+a+1,0>a&&(a=0)):a>k.length&&(a=k.length);var g=k[a];if(k=0==a?k[a]:k[a-1])for(var h=0;h<k.length;h++){var e=k[h];(b=(g||[])[h])&&b.refCell?
(b.refCell.cell.rowSpan+=1,h+=b.refCell.cell.colSpan-1):(e=e.cell||e.refCell,b=document.createElement(e.tagName),b.colSpan=e.colSpan,h+=e.colSpan-1,d&&d.call(this,b),f.appendChild(b))}else b=document.createElement("td"),d&&d.call(this,b),f.appendChild(b);((c.rows[0]||{}).parentElement||c).insertBefore(f,c.rows[a])};this.split=function(a,d){a.tagName&&(a=[a]);a=Array.prototype.slice.call(a);for(var b=0;b<a.length;b++){var c=a[b];if(!(1>=c.rowSpan&&1>=c.colSpan)){for(var f=this.matrix(),k=this.position(c,
f),g=Array(c.rowSpan),b=0;b<c.rowSpan;b++){g[b]=document.createDocumentFragment();for(var h=0;h<c.colSpan;h++)if(0!==b||0!==h){var m=document.createElement(c.tagName);d&&d.call(this,m);g[b].appendChild(m)}}c.rowSpan=c.colSpan=1;for(b=0;b<g.length;b++){c=f[k.y+b];m=null;for(h=k.x+(0===b?1:0);h<c.length;h++)c[h].cell&&(m=c[h].cell,h=c.length);e.rows[k.y+b].insertBefore(g[b],m)}}}};this.mergeVertical=function(a,d){for(var b=!1,c=0;c<n.maxIteration;c++)if(this._mergeVertical(a,d))b=!0;else break;return b};
this.mergeHorizontal=function(a,d){for(var b=!1,c=0;c<n.maxIteration;c++)if(this._mergeHorizontal(a,d))b=!0;else break;return b};this.first=function(){for(var a=this.element.rows,d=0;d<a.length;d++)for(var b=a[d].cells;0<b.length;)return b[0];return null};this.last=function(){for(var a=this.element.rows,d=a.length-1;0<=d;d--)for(var b=a[d].cells,c=b.length-1;0<=c;)return b[c];return null};this.cells=function(a,d){if(1>arguments)return[];1==arguments?(d=a,a=this.first()):"[object Array]"===Object.prototype.toString.call(a)&&
(a=this.cell.apply(this,a));if(!this.isAChildCell(a))return[];var b=[];if(!this.isAChildCell(a))return b;for(var b=d.split(/,+/g),c=[],f=this.matrix(),k=this.position(a,f),g=0;g<b.length;g++)c=c.concat(B(f[k.y][k.x],f,b[g]));return C(c)};this.cell=function(a,d,b){b=b||this.matrix();0>d&&(d=b.length+d);if(0>d||d>=b.length)return null;d=b[d];0>a&&(a=d.length+a);if(0>a||a>=d.length)return null;a=d[a];return a.cell||a.refCell.cell};this.merge=function(a,d){for(var b,c,f=!1,k=0;k<n.maxIteration;k++)if(c=
this._mergeVertical(a,d),b=this._mergeHorizontal(a,d),c||b)f=!0;else if(!c&&!b)break;return f};this._mergeVertical=function(a,d){a=z(a);if(1>=a.length)return!1;for(var b=this.matrix(),c=!1,f=0,k=a.length;f<k;f++){var g=a[f],h=[],e=g.colSpan,q=g.rowSpan;if(this.isAChildCell(g)){var u=this.position(g,b);console.dir(u);if(!u)continue;for(w=u.y+g.rowSpan;w<b.length;w++)for(var l=[],p=0,n=b[w],t=0,v=u.x;v<n.length;v++){var r=n[v].cell,t=t+((r||{}).colSpan||1),p=0===p?(r||{}).rowSpan:p;r&&A(a,r)&&t<=e&&
r.rowSpan==p?(l.push(r),e===t&&(h=h.concat(l),q+=p,v=n.length),v+=r.colSpan-1,w+=r.rowSpan-1):(v=n.length,w=b.length)}}if(0<h.length){d&&d.call(this,e,q,g,h);for(var w=0;w<h.length;w++)h[w].parentElement.removeChild(h[w]);g.rowSpan=q;g.colSpan=e;c=!0}}return c};this._mergeHorizontal=function(a,d){a=z(a);if(1>=a.length)return!1;for(var b=this.matrix(),c=!1,f=0,e=a.length;f<e;f++){var g=a[f],h=[],m=g.rowSpan,q=g.colSpan;if(this.isAChildCell(g)){var l=this.position(g,b);if(!l)continue;var n=b[l.y],p=
l.x+g.colSpan;for(l2=n.length;p<l2;p++)for(var n=[],y=0,t=0,v=l.y;v<b.length;v++){var r=b[v][p].cell,t=t+((r||{}).rowSpan||1),y=0===y?(r||{}).colSpan:y;r&&A(a,r)&&t<=m&&r.colSpan==y?(n.push(r),m===t&&(h=h.concat(n),q+=y,v=b.length),v+=r.rowSpan-1,p+=r.colSpan-1):(v=b.length,p=l2)}}if(0<h.length){d&&d.call(this,q,m,g,h);for(var p=0;p<h.length;p++)h[p].parentElement.removeChild(h[p]);g.rowSpan=m;g.colSpan=q;c=!0}}return c};this.position=function(a,d){d=d||this.matrix();for(var b=0,c;b<d.length;b++){c=
d[b];for(var f=0,e;f<c.length;f++)if((e=c[f])&&e.cell==a)return{x:e.x,y:e.y}}return null};this.matrix=function(a){var d,b=this.element,c=[],f=[],e=b.rows,b=b.innerHTML;if(n.cache&&l[b])return l[b];this.clearCache();for(var g=0;g<e.length;g++)c.push([]);for(g=0;g<e.length;g++){var h=e[g];for(var m=d=0;m<h.cells.length;m++){var q=h.cells[m];if("object"!=typeof c[g][d]&&!1!==c[g][d]){var u=a?parseInt(q.getAttribute("rowSpan"),10):q.rowSpan,u=Math.floor(Math.abs(isNaN(u)?1:u));0===u&&!a&&q.ownerDocument&&
"BackCompat"==q.ownerDocument.compatMode&&(u=1);if(1==u)if(!q.colSpan||2>q.colSpan)c[g][d]={cell:q,x:d,y:g};else{var x=c[g][d]={cell:q,x:d,y:g};for(var p=1;p<q.colSpan;p++)c[g][d+p]={refCell:x,x:d+p,y:g}}else{x=c[g][d]={cell:q,x:d,y:g};0===u&&f.push(x);for(var p=0,y=Math.max(u,1);p<y;p++)for(var t=0;t<q.colSpan;t++)if(0!==p||0!==t)x=c[g+p][d+t]={refCell:x,x:d+t,y:g+p},0===u&&f.push(x)}}else m--;d++}}if(f.length)for(g=0;g<f.length;g++)for(a=f[g],e=a.x,m=a.y+1;m<c.length;m++)for(c[m].splice(e,0,{x:e,
y:m,refCell:a.refCell||a}),h=e+1;h<c[m].length;h++)c[m][h].x+=1;n.cache&&(l[b]=c);return c};this.getCellPosition=function(a){for(var d=[],b=this.element.rows,c=0;c<b.length;c++)d.push([]);for(c=0;c<b.length;c++)for(var f=b[c].cells,e=0,g=0;g<f.length;g++){var h=f[g];if(d[c][e])g--,e++;else{if(h==a)return{x:c,y:e};for(var m=1;m<h.rowSpan;m++)for(var l=0;l<h.colSpan;l++)d[c+m][e+l]=!0;e+=h.colSpan}}};this.getCellByPosition=function(a,d){var b=[],c=this.element.rows;if(a>=c.length)return null;for(var f=
0;f<c.length;f++)b.push([]);for(var f=0,e=Math.min(c.length,a+1);f<e;f++)for(var g=c[f].cells,h=0,m=0;m<g.length;m++){var l=g[m];if(b[f][h])m--,h++;else{if(f==a&&h==d)return l;for(var n=1;n<l.rowSpan;n++)for(var x=0;x<l.colSpan;x++)b[f+n][h+x]=!0;h+=l.colSpan}}}};n.isACell=function(e){return e&&("TD"==e.tagName||"TH"==e.tagName)};n.rowSpan=function(e){if(n.isACell(e)){if(0===e.rowSpan){if(-1==e.cellIndex)return 1;e=e.parentElement;var l=1;if(!e||"TR"!=e.tagName)return-1;for(;e=e.nextSibling;)"TR"==
e.tagName&&l++;return l}return e.rowSpan}return null};n.maxIteration=50;n.cache=!0;n.build=1;n.version="0.1";n.stable=!1;window.Table=n})();